name: Drf aslmedia CI/CD Deployment

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
       - name: executing remote ssh commands using ssh-key
       - uses: appleboy/ssh-action@v0.1.10
       - with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/sarvinoz/Expenses/
            git reset --hard origin/master
            git pull 
            source /var/www/sarvinoz/Expenses/.venv/bin/activate
            pip install -r req.txt
#            make udb
            python3 manage.py makemigrations
            python3 manage.py migrate
#            DJANGO_SUPERUSER_USERNAME=admin \
#            DJANGO_SUPERUSER_EMAIL=admin@example.com \
#            DJANGO_SUPERUSER_PASSWORD=1 
#            python3 manage.py createsuperuser --noinput || true
            systemctl restart nginx.service
            systemctl restart expenses_sarvinoz.service